jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN}
        password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: "admin"
          description: "Jenkins administrators"
          permissions:
          - "Overall/Administer"
          entries:
          - user: "admin"
        - name: "readonly"
          description: "Read-only users"
          permissions:
          - "Overall/Read"
          - "Job/Read"
          entries:
          - user: "authenticated"

